Auth:
  JwtSecretKey: "AllYourBase"
  PasswordSecretKey: "dsadjflshfjghfdjkggfdj21321"
HttpServer:
  Port: 9233
  ShutdownTimeout: 2s
Database:
  Main:
    Host: '127.0.0.1'
    Port: '3306'
    User: 'root'
    Password: 'root'
    Name: 'service'
  Replica:
    Host: '127.0.0.1'
    Port: '3306'
    User: 'root'
    Password: 'root'
    Name: 'service'
Transport:
  User:
    Host: http://127.0.0.1:9235
    Timeout: 5s
